# Data sources

## Home Value Data
Our goal is to explore how U.S. real estate prices in different states/cities change over the years and how economic variables effect these prices. As such, we obtained our primary dataset, which contain home value information, from Zillow's housing data division (https://www.zillow.com/research/data/). 

Although there are many well-known real estate websites that can provide similar data, such as foreclosure and realtor, we ultimately chose the data from Zillow as our home value resource. Zillow is the premier real estate website in the US. Not only does  Zillow provide services to customers for selling, buying, renting and financing in real estate industry, the company also has a research division that focuses on collecting the most up-to-date real estate information in the US market. Their research includes home value, inventory, sale price, etc. We trust Zillow's database because the company is open about data sources and respects the integrity of data. (https://www.zillow.com/research/about-us/) Furthermore, the Zillow Research team states that the purpose of their research is not aimed at business profit and the team also made the code open sourced to ensure the accuracy in their home value data. The research team collects their data using their Econ Data API which can be reached from the Postman website. (https://documenter.getpostman.com/view/9197254/SzRuZCCj?version=latest)

We obtained the original data set about home value in a monthly and city level base. The raw data set contains 5 categorical variables to describe the region and name of city or state. It also has the information about size rank and region type. Home value are described through Zillow Home Value Index (ZHVI, the home value measurement in different regions within the US. The detail of the methodology of Zillow Home Value Index can be found in the Zillow Research methodology introduction website. (https://www.zillow.com/research/zhvi-methodology-2019-deep-26226/) We have monthly home value for each city from 01/31/00 to 10/31/21 (in total 250 months). 

The potential problems of this dataset can be divided into two aspects. First, we have a significant amount of missing data for the Zillow Home Value Index, especially for early years around 2010. Second, the dataset was too granular and drilled down to the city level for each month within the past ten years. If we continue to focus on city and monthly level data, it could conceal the trend of the data could make the graph hard by cluttering the analysis.

## Other Variables

Before we officially start the exploratory data analysis, we discussed the key economic variables that could potentially influence home value. After brainstorming and research, we decided to focus on the most interesting variables: population, hosing unit, income and unemployment rate in the corresponding states.
We obtained the above mentioned data for each state from 2010 to 2019 using the  Census Bureau official website (https://www.census.gov). To be more specific, each resource and related methodology are listed below:

### Population

Source: https://www.census.gov/data/tables/time-series/demo/popest/2010s-state-total.html  
Methodology https://www2.census.gov/programs-surveys/popest/technical-documentation/methodology/2010-2019/natstcopr-methv2.pdf.

### Housing unit

Source: https://www2.census.gov/programs-surveys/popest/tables/2010-2019/housing/totals/NST-EST2019-ANNHU.xlsx  
Methodology: https://www2.census.gov/programs-surveys/popest/technical-documentation/methodology/2010-2019/2019-hu-meth.pdf

### Income
Source: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiBueaZ0tH0AhWKmHIEHZ-WBasQFnoECBYQAQ&url=https%3A%2F%2Fwww2.census.gov%2Fprograms-surveys%2Fcps%2Ftables%2Ftime-series%2Fhistorical-income-households%2Fh08.xls&usg=AOvVaw0MqyTNSJP8VVd2wWKeoHeo

### Unemployment Rate
Additionally, we also used the unemployment rate 2010-2018 gathered by Local Area Unemployment Statistics, U.S. Bureau of Labor Statistics (BLS) and stored in the Iowa state university community indicators program dataset
Source: https://www.icip.iastate.edu/tables/employment/unemployment-states
We added the 2019 unemployment rate using the record of BLS official website: https://www.bls.gov/lau/lastrk19.htm

